<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CSIS Personal Data Protection Policy__78e109</name>
   <tag></tag>
   <elementGuidId>7b27316c-641c-4b15-be78-1a4f0d6b6558</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#declarationTerms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='declarationTerms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#declarationTerms</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d00af189-93b0-453b-ad88-7342b20f59e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>declarationTerms</value>
      <webElementGuid>022accb1-d485-415e-b54a-03abd12d0dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>declarationTerms</value>
      <webElementGuid>415b35b0-f5a3-4951-a5ba-adac1db942c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9db28283-cc6f-40bc-83af-1f6f663ce6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer h-4 w-4 text-[#313984] focus:ring-[#313984] rounded check-box-custom</value>
      <webElementGuid>fdd5b8bf-06fc-4b91-915c-100e26a0a5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f833c8b2-d843-4488-a5ea-111a7afb2ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;declarationTerms&quot;)</value>
      <webElementGuid>e4ee05de-c006-43f2-bbc4-8145445fa7e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='declarationTerms']</value>
      <webElementGuid>54586698-bbee-44ce-88bf-78d5a0922211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/div[6]/div/div[2]/div/input</value>
      <webElementGuid>f33cc0cd-b84e-4985-9bc4-487ab784b712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/input</value>
      <webElementGuid>9be3f355-a534-4d7f-adea-b848023245d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'declarationTerms' and @name = 'declarationTerms' and @type = 'checkbox']</value>
      <webElementGuid>0b5c36ba-7021-487b-9145-7a17dea36a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/div[4]/div/div[2]/div/input</value>
      <webElementGuid>0ae6860b-faed-450a-a6e4-b54ab161dee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/input</value>
      <webElementGuid>4a1328f6-d741-463e-8c58-e9cf22704690</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
