<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Declaration_declarationPolicy</name>
   <tag></tag>
   <elementGuidId>0c2427d5-11c2-4a96-99dc-491b79f53ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#declarationPolicy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='declarationPolicy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#declarationPolicy</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b591202e-7187-4e0d-bc37-afa3154f8808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>declarationPolicy</value>
      <webElementGuid>96be57fe-7eda-4df0-bca9-823ee724b10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>declarationPolicy</value>
      <webElementGuid>5e994a6f-4071-4d91-a4f4-68979d6ab1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0fb2ba6e-9c27-4f6c-b919-6fe60a5bfba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer h-4 w-4 text-[#313984] focus:ring-[#313984] rounded check-box-custom</value>
      <webElementGuid>54efb1d1-3f57-4ae4-82a2-e876de3324a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dd440a60-3f68-4d84-932b-7eb2cde552f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;declarationPolicy&quot;)</value>
      <webElementGuid>322dc0f0-3cf1-48aa-ad35-41170bd4b937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='declarationPolicy']</value>
      <webElementGuid>9f668298-d4c8-43a1-b1c0-fbed77c718f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/div[6]/div/div/div/input</value>
      <webElementGuid>23e09ed6-adac-49e3-8500-61cf33c42f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>6f72ed84-5198-4cb9-b553-a7bde3606288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'declarationPolicy' and @name = 'declarationPolicy' and @type = 'checkbox']</value>
      <webElementGuid>244d80de-b1ca-406e-993a-333bcbec5ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/div[4]/div/div/div/input</value>
      <webElementGuid>57193dbb-1bc2-456d-bd92-533f678df17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>e9ee3736-c7de-42ee-adfc-5e4cb6757381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
