<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CSIS Personal Data Protection Policy__78e109</name>
   <tag></tag>
   <elementGuidId>7b27316c-641c-4b15-be78-1a4f0d6b6558</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#declarationTerms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='declarationTerms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#declarationTerms</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c00ef59d-1b34-4a7a-b6c1-70f24ae65a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>declarationTerms</value>
      <webElementGuid>c0db5ee7-7a5c-4934-bf2b-aa4e182f7b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>declarationTerms</value>
      <webElementGuid>b6a7b61b-5ced-4197-8b8d-c37c82de58b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>46b3a00b-5118-4a81-bbb6-095bc2342ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer h-4 w-4 text-[#313984] focus:ring-[#313984] rounded check-box-custom</value>
      <webElementGuid>9d7a97af-f148-47ba-bdfb-55d6abef12c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a7bdea2f-e1c7-4544-8a81-5e0be2780f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;declarationTerms&quot;)</value>
      <webElementGuid>2b0c6d58-ecaa-49a2-8e0d-847adcbaf96b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='declarationTerms']</value>
      <webElementGuid>74e38d4e-0849-4f81-ad82-6130d029d29a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/div[4]/div/div[2]/div/input</value>
      <webElementGuid>0ae6860b-faed-450a-a6e4-b54ab161dee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/input</value>
      <webElementGuid>4a1328f6-d741-463e-8c58-e9cf22704690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'declarationTerms' and @name = 'declarationTerms' and @type = 'checkbox']</value>
      <webElementGuid>a17559ec-6b4d-4ce3-b0fc-2df2135ef1cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
