<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Declaration_declarationPolicy</name>
   <tag></tag>
   <elementGuidId>0c2427d5-11c2-4a96-99dc-491b79f53ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#declarationPolicy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='declarationPolicy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#declarationPolicy</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d277009-aaa9-40a9-8a03-205ba3bef54f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>declarationPolicy</value>
      <webElementGuid>5334fb49-7bbf-49ac-be27-0f9e1e536b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>declarationPolicy</value>
      <webElementGuid>f212b5f3-c351-44b9-abab-5e52048044f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d8d75e35-68dd-456c-9c8f-708db12278d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer h-4 w-4 text-[#313984] focus:ring-[#313984] rounded check-box-custom</value>
      <webElementGuid>22aa56c0-1dc6-4278-ae8c-9411d5bbbdce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f1f70663-1436-4414-830b-b85bf21d9206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;declarationPolicy&quot;)</value>
      <webElementGuid>e41cc18d-cee0-4b9b-893a-c6e3978f4a82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='declarationPolicy']</value>
      <webElementGuid>70c314d1-86d1-42fa-812f-0bbc56aaef7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/div[4]/div/div/div/input</value>
      <webElementGuid>57193dbb-1bc2-456d-bd92-533f678df17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>e9ee3736-c7de-42ee-adfc-5e4cb6757381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'declarationPolicy' and @name = 'declarationPolicy' and @type = 'checkbox']</value>
      <webElementGuid>4e56df5e-3e82-49ff-9907-9463d31d5961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
