<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__lastName</name>
   <tag></tag>
   <elementGuidId>25f22107-5a85-486a-a2ee-0469997f086a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;lastName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='lastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;lastName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>817939b9-a60e-4003-a856-3f5722a1c4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full custom-input mt-5</value>
      <webElementGuid>a57dd464-87cf-45eb-b7ca-62e4c7972b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d465704f-e9cb-4189-aedf-19dfade832fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>6ea0e109-9b28-4c25-aaea-aa0f790cf4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3c047813-7460-4842-92c7-18ddcce93d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>J</value>
      <webElementGuid>84301e1e-2caf-417e-98e7-48dad384e125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;main-page-bg&quot;]/div[2]/div[@class=&quot;main-page-section&quot;]/div[@class=&quot;signup-selection&quot;]/div[@class=&quot;flex flex-wrap justify-center&quot;]/div[@class=&quot;w-full 2xl:pt-10 lg:pt-10 md:pt-5&quot;]/div[@class=&quot;relative flex flex-col min-w-0 break-words bg-white w-full mb-6&quot;]/div[@class=&quot;2xl:pb-14 2xl:pt-10 lg:pb-14 pb-7 pt-5 lg:pt-10 flex-auto&quot;]/div[@class=&quot;tab-content tab-space&quot;]/div[@class=&quot;grid grid-cols-12 gap-2&quot;]/div[@class=&quot;col-span-12&quot;]/div[@class=&quot;corporate-signup-sec&quot;]/div[@class=&quot;Fields-information-sec&quot;]/div[@class=&quot;organisation-info-sec&quot;]/div[@class=&quot;grid grid-cols-12 gap-4&quot;]/div[@class=&quot;xl:col-span-12 md:col-span-12 col-span-12&quot;]/div[@class=&quot;2xl:mt-12 lg:mt-12 mt-5&quot;]/div[@class=&quot;grid grid-cols-12 2xl:gap-6 lg:gap-6 gap-3&quot;]/div[@class=&quot;input-sec-texts 2xl:col-span-6 lg:col-span-6 md:col-span-12 col-span-12&quot;]/div[@class=&quot;flield-sec&quot;]/div[@class=&quot;w-full&quot;]/input[@class=&quot;w-full custom-input mt-5&quot;]</value>
      <webElementGuid>dd845381-0029-4ac0-b64c-5db810a288e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='lastName']</value>
      <webElementGuid>d1087867-81d0-43bd-9d69-a92667d0a35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>00aad341-968f-4e53-8f94-c85a970d4bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>7ad68715-37f0-407d-9d38-118613ec63d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'lastName']</value>
      <webElementGuid>9d18d9de-d811-4f9d-924b-d173c5521abb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
