<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__isCheck</name>
   <tag></tag>
   <elementGuidId>d048b7c0-912d-4a41-89d6-d4837aebd6f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isCheck</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isCheck']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#isCheck</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8192f4a7-8a7d-4601-a10e-9960ef8f70c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isCheck</value>
      <webElementGuid>3f21858d-6320-4707-b583-892ac351d2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isCheck</value>
      <webElementGuid>99ec22ee-f481-4656-81f6-31a277a6a465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>24e57226-cd3c-4170-8477-4daef3043607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer h-4 w-4 text-[#C00000] focus:ring-[#C00000] rounded check-box-custom</value>
      <webElementGuid>c029f2f4-d223-4898-96da-806b1c209997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9e5a415e-6e9b-4ebb-b9b3-44e36adbba9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isCheck&quot;)</value>
      <webElementGuid>7c62d16d-e59a-4e02-8431-5891ea8bbf81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isCheck']</value>
      <webElementGuid>78c048e6-d04b-4f21-ab4e-f99edcb6d33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div[4]/div/div/input</value>
      <webElementGuid>3fce9afa-e795-4fc9-a2cf-90de66e97b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div/div/input</value>
      <webElementGuid>6a71871f-851a-4ed6-9601-f2ee9b857ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'isCheck' and @name = 'isCheck' and @type = 'checkbox']</value>
      <webElementGuid>fc6cfba8-c83b-4b16-9c60-7fbfe96cb978</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
