<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__OrganisationList</name>
   <tag></tag>
   <elementGuidId>3472e7ef-a031-4e28-baef-089eb9235aa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eventName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='eventName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#eventName</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e2694f1-7180-4da7-b37e-f8392c7756fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eventName</value>
      <webElementGuid>bc148e51-9f0d-4427-8b73-48e3889fab0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OrganisationList</value>
      <webElementGuid>a9d58bbc-bc77-4094-814e-c769187f8a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-input btn btn-dropdown justify-between font-normal py-3 w-full border-[#757575] text-[#C00000] px-4</value>
      <webElementGuid>ff76726c-b296-4d47-ba91-3711873ffa71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a17fb5dd-c000-46cd-a698-8b6174d2a176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f26b0d5d-b932-4ce1-b99d-9a82d004cac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventName&quot;)</value>
      <webElementGuid>ae96f794-7af7-403f-a08a-0ed761adda80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eventName']</value>
      <webElementGuid>b9743699-425a-4776-ac12-8848f5ed9a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[7]/div/div/input</value>
      <webElementGuid>9944898f-64ce-49cd-bf57-2cd69aaecce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>a244c30e-3531-4595-a6cf-16fad68c1eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'eventName' and @name = 'OrganisationList' and @type = 'text']</value>
      <webElementGuid>0e1973a5-66bb-4c73-aef2-72efe7dec3da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
