<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Corporate_radio-buttons</name>
   <tag></tag>
   <elementGuidId>bf1ffbf1-50f6-44ae-a730-46bf9da3ad97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IndividualType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IndividualType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#IndividualType</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9aa17a8-6e39-460d-b683-4cbae6101200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>43fd902d-db6c-4979-8e6d-379dad0083f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-buttons</value>
      <webElementGuid>5948fc9b-97d8-489f-8e52-9c419351f584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IndividualType</value>
      <webElementGuid>ff0243a8-ff6e-4fa5-b159-0e40e8545c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-radio</value>
      <webElementGuid>b4e56151-39dd-436d-8d76-16a38f816c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>723c8a94-5360-408b-8218-d23938bead8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#link2</value>
      <webElementGuid>6fff6e54-5a6a-4f15-ae1e-37eaea58741f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tablist</value>
      <webElementGuid>d79f36fb-e121-4e64-be35-dd2fa4774895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Individual</value>
      <webElementGuid>86c00043-1252-4a92-82a2-9842a720d776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IndividualType&quot;)</value>
      <webElementGuid>f72cc85b-86b3-4a9d-8711-c1e9a99d46dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IndividualType']</value>
      <webElementGuid>049c5bf9-32b8-490e-b2ce-673694c1a1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div/ul/li[2]/input</value>
      <webElementGuid>d73f5571-ccf4-455b-9457-03316e1d1a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>5fad3ab4-01bf-4e30-88c0-89c8a56ecd07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'radio-buttons' and @id = 'IndividualType' and @href = '#link2']</value>
      <webElementGuid>787d6d40-a8a1-4b72-a00f-f849bbf4a24e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
